In [81]:
import pandas as pd
import numpy as np
import seaborn as sns

In [82]:
df = pd.read_csv('emails.csv')
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5721  Subject: re : research and development charges...     0
5722  Subject: re : receipts from visit  jim ,  than...     0
5723  Subject: re : enron case study update  wow ! a...     0
5724  Subject: re : interest  david ,  please , call...     0
5725  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5726 rows x 2 columns]

In [83]:
df['spam'].value_counts()

0    4358
1    1368
Name: spam, dtype: int64

In [84]:
df.drop_duplicates(inplace = True)
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5721  Subject: re : research and development charges...     0
5722  Subject: re : receipts from visit  jim ,  than...     0
5723  Subject: re : enron case study update  wow ! a...     0
5724  Subject: re : interest  david ,  please , call...     0
5725  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5693 rows x 2 columns]

In [85]:
df['spam'].value_counts()

0    4325
1    1368
Name: spam, dtype: int64

In [86]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [87]:
x = df.text.values

In [88]:
y = df.spam.values

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

# Data Preprocessing

In [91]:
from sklearn.feature_extraction.text import CountVectorizer

In [92]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [93]:
x_train.toarray()

array([[2, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [94]:
from sklearn.naive_bayes import MultinomialNB

In [95]:
MNB = MultinomialNB()

In [96]:
MNB.fit(x_train, ytrain)

MultinomialNB()

In [97]:
x_test = cv.transform(xtest)

In [98]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [99]:
MNB.score(x_test, ytest)

0.9912203687445127

In [100]:
emails = ['Hey, I need to contact with you as soon as possible', 'Congrats, You have got a new Iphone 14 give away. Please do the survey, click link below']

In [101]:
cv_emails = cv.transform(emails)

In [102]:
MNB.predict(cv_emails)

array([0, 1], dtype=int64)